// All user-facing copy lives here so it can be translated later.
// Tone: a thoughtful friend. Never a coach, never a nag.

const zhCN = {
  appName: 'US',
  common: {
    save: '保存',
    saved: '已保存',
    cancel: '算了',
    back: '返回',
    confirm: '确定',
    loading: '稍等…',
    you: '你',
    unnamed: '还没有名字',
    somethingWrong: '出了点小问题，再试一次好吗？',
    optional: '可不填',
  },
  nav: {
    home: 'US',
    intentions: 'Intentions',
    me: 'Me',
  },
  photo: {
    take: '拍一张',
    pick: '从相册选',
    remove: '去掉照片',
    cancel: '算了',
    avatar: '头像',
    cover: '这段关系的照片',
    change: '换一张照片',
    failed: '照片没能放上去，再试一次好吗？',
  },
  presets: {
    family: '家人',
    partners: '伴侣',
    friends: '朋友',
    work: '同事',
    other: '其他',
    none: '不贴标签',
  },
  states: {
    active: '',
    quiet: '安静中',
    closed: '已合上',
  },
  login: {
    title: '欢迎回来',
    intro: '这里只属于你和你在乎的人。',
    noEmail: '先不用邮箱，直接开始',
    noEmailHint: '身份只保存在这台手机的这个浏览器里。换手机或清除浏览器数据就找不回来了，之后可以在 Me 里绑定邮箱。',
    emailLabel: '你的邮箱',
    emailPlaceholder: 'name@example.com',
    sendCode: '发送验证码',
    sending: '正在发送…',
    codeSent: (email: string) => `验证码已经发到 ${email}。如果没看到，看看垃圾邮件。`,
    codeLabel: '6 位验证码',
    verify: '进入',
    verifying: '正在确认…',
    changeEmail: '换一个邮箱',
    invalidCode: '验证码好像不对，或者已经过期了。',
    rateLimited: '发送得有点频繁，过一会儿再试吧。',
  },
  onboarding: {
    title: '大家怎么称呼你？',
    hint: '只有和你在同一个 US 里的人会看到。',
    namePlaceholder: '比如：小林',
    continue: '好了',
  },
  home: {
    empty: '这里还很安静。\n先为一段关系建一个 US 吧。',
    create: '新建一个 US',
    reorder: '调整顺序',
    doneReorder: '好了',
    moveUp: '上移',
    moveDown: '下移',
    hiddenSection: (n: number) => `收起来的（${n}）`,
    onlyMe: '只有你',
  },
  createUs: {
    title: '新建一个 US',
    nameLabel: '叫它什么',
    namePlaceholder: '比如：我们俩、林家、东京三人组',
    descLabel: '想怎么描述你们',
    descPlaceholder: '我们是在东京认识的朋友',
    presetLabel: '如果愿意，选一个标签',
    stageLabel: '你们现在的阶段',
    stagePlaceholder: '比如：朋友、恋人、异地',
    stageSinceLabel: '大概从什么时候开始',
    submit: '建好了',
    soloNote: '一个人也可以先建好，之后再邀请别人。',
  },
  us: {
    about: '关于我们',
    members: '在这里的人',
    nothingYet: '回忆会在这里慢慢出现。',
    quietNote: '这个 US 现在很安静。想回来的时候，它一直在。',
    closedNote: '这个 US 已经合上了。过去的一切都还在，只是不再添新的。',
    proposalWaiting: '有一个提议，等你看看。',
    seen: 'Seen',
    aboutShort: 'About',
    together: '想一起做的',
    addTogether: '再写一件',
    today: '今天',
  },
  about: {
    title: '关于我们',
    descriptionPlaceholder: '写一句关于你们的话',
    inviteOne: '邀请一个人',
    inviteHint: '每个链接只能用一次，7 天内有效。对方不需要注册就能进来。',
    createInvite: '生成一个邀请链接',
    share: '发送链接',
    copy: '复制链接',
    copied: '已复制',
    inviteShareText: (name: string) => `我在 US 里为「${name}」留了一个位置，点开就能进来：`,
    openInvites: '还没被用掉的链接',
    inviteCreatedAt: (d: string) => `${d} 生成`,
    revoke: '收回',
    changeName: '改名字或标签',
    changeStage: '关系有了变化',
    changeState: '这个 US 的状态',
    togetherHint: '需要每个人都同意，才会改。',
    waiting: '等大家决定',
    proposedBy: (name: string) => `${name} 提议`,
    proposalKind: '想改什么',
    kinds: {
      rename: '名字',
      relabel: '标签',
      stage: '关系阶段',
      state: '状态',
    },
    newName: '新名字',
    newStage: '现在是什么关系',
    stageDate: '从哪天开始',
    stateLink: {
      active: '让它安静一阵子，或者合上',
      quiet: '让它热闹起来，或者合上',
      closed: '重新打开它',
    },
    stateOptions: {
      active: '重新热闹起来',
      quiet: '安静一阵子',
      closed: '合上（不再添新内容，过去的都保留）',
    },
    propose: '提出来',
    proposalText: {
      rename: (v: string) => `把名字改成「${v}」`,
      relabel: (v: string) => `把标签改成「${v}」`,
      stage: (v: string, d: string) => `把关系写成「${v}」，从 ${d} 开始`,
      state: (v: string) => `让这个 US ${v}`,
    },
    accept: '同意',
    decline: '婉拒',
    waitingOthers: '你已经同意了，等其他人看看。',
    withdraw: '撤回',
    history: '我们走过的阶段',
    historyEmpty: '写下你们现在是什么关系',
    historyUnknownDate: '某个时候',
    hide: '从我的视野里收起',
    hideHint: '只对你自己生效，其他人不会知道。',
    unhide: '放回首页',
    leave: '离开这个 US',
  },

  leave: {
    title: '离开这个 US',
    intro: '你随时可以离开，不需要任何人同意。',
    keep: '保留我留下的内容',
    keepHint: '其他人还能看到你写过的东西。',
    remove: '带走我的内容',
    removeHint: '你写的内容会被删除。别人写的不会受影响。',
    exportFirst: '离开之前，可以先导出你想留下的东西。',
    confirm: '确定离开',
    lastOne: '你是这里最后一个人。离开后，这个 US 会安静地留在那里，不会再有人看到。',
  },
  invite: {
    loading: '正在打开邀请…',
    invalid: '这个链接已经用过、被收回，或者过期了。\n可以请对方再发一个。',
    title: (name: string) => `「${name}」`,
    whoIsHere: (names: string) => `${names} 在这里等你。`,
    nameLabel: '大家怎么称呼你？',
    enter: '进来吧',
    entering: '正在进入…',
    haveAccount: '我有账号，用邮箱登录',
    guestNote: '不需要注册。以后想换手机也能找回，可以在 Me 里绑定邮箱。',
  },
  memory: {
    add: '留下一段回忆',
    newTitle: '留下一段回忆',
    editTitle: '修改这段回忆',
    bodyLabel: '发生了什么',
    bodyPlaceholder: '那天的天气、说过的话、一个小细节……',
    dateLabel: '什么时候',
    precision: {
      day: '记得是哪一天',
      month: '只记得哪个月',
      year: '只记得哪一年',
    },
    placeLabel: '在哪里',
    placePlaceholder: '比如：镰仓的海边',
    photos: '照片',
    addPhotos: '添加照片',
    voice: '声音',
    removeMedia: '移除',
    save: '留下来',
    saving: '正在保存…',
    edit: '修改',
    delete: '删除这段回忆',
    deleteConfirm: '确定删除吗？如果别人在这段回忆下写了自己的版本，他们写的会留下。',
    by: (name: string) => `${name} 记下的`,
    byMe: '你记下的',
    removedShell: '这段回忆的原文已经被作者带走了。',
    hasVoice: '有一段声音',
    photoCount: (n: number) => `${n} 张照片`,
    empty: '回忆会在这里慢慢出现。',
    tooMany: '一段回忆最多放 12 个照片或声音。',
    uploadFailed: '有文件没能上传，可以稍后在"修改"里再试。',
  },
  recorder: {
    start: '录一段声音',
    stop: '停下',
    recording: (s: string) => `正在录音 ${s}`,
    denied: '没有拿到麦克风权限。可以在系统设置里允许后再试。',
    unsupported: '这个浏览器暂时不支持录音。',
    discard: '重录',
  },
  perspective: {
    prompt: '你记得的版本是？',
    hint: '每个人记得的都不一样。写下你的，就能看到别人记得的。',
    placeholder: '从你的角度，那天是什么样子的？',
    private: '只给自己看',
    privateTag: '只有你能看到',
    submit: '写好了',
    skip: '跳过，直接看',
    mine: '你记得的',
    others: '大家记得的',
    noneYet: '还没有其他人的版本。',
    writeMine: '写下你的版本',
    edit: '修改',
    remove: '删掉我的版本',
    removeConfirm: '删掉你写的这个版本吗？',
    closedHint: '这个 US 已经合上，不能再写新的版本了。',
    someone: 'TA',
  },
  seen: {
    title: '我看见的你',
    intro: '写给某个人：最近你在 TA 身上看见的好。只有你们两个人能看到。',
    linkFromUs: '我看见的你',
    to: '写给谁',
    placeholder: '比如：那天你明明很累，还是先问我吃饭了没有。',
    give: '交给 TA',
    given: '已经交给 TA 了。',
    toMe: '写给你的',
    fromMe: '你写下的',
    toWhom: (name: string) => `写给 ${name}`,
    from: (name: string) => `${name} 写给你`,
    keep: '收好',
    kept: '已收好',
    takeBack: '收回',
    takeBackConfirm: '收回这张纸条吗？TA 将不再看到它。',
    nobody: '等有人加入后，就可以写给 TA 了。',
    noneToMe: '还没有。',
    collection: '收好的「我看见的你」',
    collectionEmpty: '还没有收好的纸条。收到的时候，可以把想留下的收在这里。',
    inUs: (name: string) => `在「${name}」`,
  },
  question: {
    label: '这周的问题',
    answer: '想到了一件事',
    answerSeen: '写给 TA',
    later: '这周都在这里，不着急。',
  },
  intention: {
    tab: '想做的事',
    title: '想做的事',
    newTitle: '想做的一件事',
    noPrompt: '有没有一件想为谁做的事？',
    pickUs: '为了哪段关系',
    bodyLabel: '一件具体的事',
    bodyPlaceholder: '比如：周六给妈妈打个电话，问问她的腰好些没有',
    visibility: {
      private: '只有我知道',
      shared: '我们一起',
    },
    visibilityHint: {
      private: '不会出现在任何人那里，也不会有任何暗示。',
      shared: '会作为一个共同的计划，出现在这个 US 里。',
    },
    save: '记下了',
    saved: '记下了。去做吧，这里会等你。',
    open: '还没做的',
    done: '做到了的',
    letGo: '放下了的',
    emptyOpen: '现在没有要做的事。也很好。',
    add: '写一件想做的事',
    markDone: '做到了',
    letGoAction: '放下',
    letGoConfirm: '放下这件事吗？没关系，以后想做还可以重新拿起来。',
    pickUp: '重新拿起来',
    seeMemory: '看看那段回忆',
    noUs: '先建一个 US，再写想做的事。',
    inUs: (name: string) => `为「${name}」`,
    ourPlans: '我们一起想做的事',
    myPrivate: '只有你知道的',
  },
  done: {
    title: '做到了。',
    intro: '真好。想把这件事留下来吗？',
    asMemory: '存为我们的回忆',
    asMemoryHint: '这个 US 里的人都会看到这段回忆。',
    asNote: '只留一句给自己',
    notePlaceholder: '那时候的心情、对方的反应……',
    saveNote: '留下',
    nothing: '不用了，就这样',
  },
  timeline: {
    title: '我们的时间线',
    stageChange: (from: string | null, to: string | null) => (from ? `${from} → ${to ?? ''}` : `从「${to ?? ''}」开始`),
    intentionDone: (body: string) => `一起做到了：${body}`,
    fromPlan: '我们一起想做的事',
  },
  export: {
    title: '导出我的数据',
    intro: '你写下的一切，加上你能看到的共享内容，会被打包成一个 ZIP 文件：里面是 JSON 数据和照片、声音的原文件。',
    start: '开始导出',
    working: (done: number, total: number) => `正在打包… ${done}/${total}`,
    collecting: '正在整理…',
    ready: '好了，文件已经开始下载。',
    again: '再导出一次',
    readme: [
      'US 数据导出',
      '',
      'data.json 包含你能看到的全部内容：你所在的 US、成员的称呼、关系历程、回忆、各自的版本、想做的事、我看见的你。',
      'media/ 文件夹里是照片和声音的原始文件，文件路径与 data.json 中的 storage_path / audio_path / avatar_path / cover_path 对应。',
      '',
      '这份文件只属于你。请妥善保存。',
    ].join('\n'),
  },
  reminder: {
    title: '每周一次的提醒',
    intro: '每周最多一条，只是轻轻提一下这周的问题。不回应也不会再提醒。',
    on: '打开提醒',
    off: '关掉提醒',
    isOn: (day: string, hour: number) => `会在每${day} ${hour}:00 左右提醒你。`,
    day: '哪一天',
    hour: '几点',
    days: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
    unsupported: '这个浏览器不支持推送提醒。US 不需要它也能正常使用。',
    iosHint: '在 iPhone 上，需要先用 Safari 把 US "添加到主屏幕"，再从主屏幕打开，才能打开提醒。',
    denied: '通知权限被关掉了，可以在系统设置里重新允许。',
    pushBody: '这周的问题在等你。有空的时候看看就好。',
  },
  install: {
    hint: '想像 App 一样使用？在 Safari 里点"分享"，再选"添加到主屏幕"。',
  },
  me: {
    title: '我',
    nameLabel: '大家怎么称呼你',
    guestTitle: '你现在是访客',
    guestHint: '访客身份只存在这台设备的这个浏览器里。绑定邮箱后，换手机、清缓存也不会丢。',
    bindEmail: '绑定邮箱',
    bindSent: (email: string) => `验证码已经发到 ${email}。`,
    bindDone: '已经绑定好了。',
    emailLine: (email: string) => `登录邮箱：${email}`,
    signOut: '退出登录',
    seenCollection: '收好的「我看见的你」',
    color: '你的颜色',
    colorHint: '你在所有 US 里都是这个颜色。',
    export: '导出我的数据',
    signOutGuestWarn: '你还没绑定邮箱，退出后这个访客身份就找不回来了。确定退出吗？',
  },
} as const;

export default zhCN;
