// All user-facing copy lives here so it can be translated later.
// Tone: a thoughtful friend. Never a coach, never a nag.

const zhCN = {
  appName: 'US',
  common: {
    save: '保存',
    saved: '已保存',
    cancel: '算了',
    back: '返回',
    confirm: '确定',
    loading: '稍等…',
    you: '你',
    unnamed: '还没有名字',
    somethingWrong: '出了点小问题，再试一次好吗？',
    optional: '可不填',
  },
  nav: {
    home: '我的人',
    me: '我',
  },
  presets: {
    family: '家人',
    partners: '伴侣',
    friends: '朋友',
    work: '同事',
    other: '其他',
    none: '不贴标签',
  },
  states: {
    active: '',
    quiet: '安静中',
    closed: '已合上',
  },
  login: {
    title: '欢迎回来',
    intro: '这里只属于你和你在乎的人。',
    emailLabel: '你的邮箱',
    emailPlaceholder: 'name@example.com',
    sendCode: '发送验证码',
    sending: '正在发送…',
    codeSent: (email: string) => `验证码已经发到 ${email}。如果没看到，看看垃圾邮件。`,
    codeLabel: '6 位验证码',
    verify: '进入',
    verifying: '正在确认…',
    changeEmail: '换一个邮箱',
    invalidCode: '验证码好像不对，或者已经过期了。',
    rateLimited: '发送得有点频繁，过一会儿再试吧。',
  },
  onboarding: {
    title: '大家怎么称呼你？',
    hint: '只有和你在同一个 US 里的人会看到。',
    namePlaceholder: '比如：小林',
    continue: '好了',
  },
  home: {
    empty: '这里还很安静。\n先为一段关系建一个 US 吧。',
    create: '新建一个 US',
    reorder: '调整顺序',
    doneReorder: '好了',
    moveUp: '上移',
    moveDown: '下移',
    hiddenSection: (n: number) => `收起来的（${n}）`,
    onlyMe: '只有你',
  },
  createUs: {
    title: '新建一个 US',
    nameLabel: '叫它什么',
    namePlaceholder: '比如：我们俩、林家、东京三人组',
    descLabel: '想怎么描述你们',
    descPlaceholder: '我们是在东京认识的朋友',
    presetLabel: '如果愿意，选一个标签',
    stageLabel: '你们现在的阶段',
    stagePlaceholder: '比如：朋友、恋人、异地',
    stageSinceLabel: '大概从什么时候开始',
    submit: '建好了',
    soloNote: '一个人也可以先建好，之后再邀请别人。',
  },
  us: {
    about: '关于我们',
    members: '在这里的人',
    nothingYet: '回忆会在这里慢慢出现。',
    quietNote: '这个 US 现在很安静。想回来的时候，它一直在。',
    closedNote: '这个 US 已经合上了。过去的一切都还在，只是不再添新的。',
    proposalWaiting: '有一个提议，等你看看。',
  },
  about: {
    title: '关于我们',
    description: '描述',
    descriptionPlaceholder: '写点什么，或者什么都不写',
    invite: '邀请',
    inviteHint: '每个链接只能用一次，7 天内有效。对方不需要注册就能进来。',
    createInvite: '生成一个邀请链接',
    share: '发送链接',
    copy: '复制链接',
    copied: '已复制',
    inviteShareText: (name: string) => `我在 US 里为「${name}」留了一个位置，点开就能进来：`,
    openInvites: '还没被用掉的链接',
    inviteCreatedAt: (d: string) => `${d} 生成`,
    revoke: '收回',
    proposals: '一起决定的事',
    proposalsHint: '改名字、标签、阶段，或者合上这个 US，需要每个人都同意。',
    newProposal: '提一个建议',
    proposalKind: '想改什么',
    kinds: {
      rename: '名字',
      relabel: '标签',
      stage: '关系阶段',
      state: '状态',
    },
    newName: '新名字',
    newStage: '新的阶段',
    stageDate: '从哪天开始',
    newState: '想让它',
    stateOptions: {
      active: '重新热闹起来',
      quiet: '安静一阵子',
      closed: '合上（不再添新内容，过去的都保留）',
    },
    propose: '提出来',
    proposalText: {
      rename: (v: string) => `把名字改成「${v}」`,
      relabel: (v: string) => `把标签改成「${v}」`,
      stage: (v: string, d: string) => `关系阶段变成「${v}」（${d}）`,
      state: (v: string) => `让这个 US ${v}`,
    },
    accept: '同意',
    decline: '婉拒',
    waitingOthers: '你已经同意了，等其他人看看。',
    withdraw: '撤回',
    outcomeApplied: '大家都同意了。',
    outcomeDeclined: '这次没有通过，没关系。',
    history: '我们走过的阶段',
    historyEmpty: '还没有记录。',
    historyUnknownDate: '某个时候',
    hide: '从我的视野里收起',
    hideHint: '只对你自己生效，其他人不会知道。',
    unhide: '放回首页',
    leave: '离开这个 US',
  },
  leave: {
    title: '离开这个 US',
    intro: '你随时可以离开，不需要任何人同意。',
    keep: '保留我留下的内容',
    keepHint: '其他人还能看到你写过的东西。',
    remove: '带走我的内容',
    removeHint: '你写的内容会被删除。别人写的不会受影响。',
    exportFirst: '离开之前，可以先导出你想留下的东西。',
    confirm: '确定离开',
    lastOne: '你是这里最后一个人。离开后，这个 US 会安静地留在那里，不会再有人看到。',
  },
  invite: {
    loading: '正在打开邀请…',
    invalid: '这个链接已经用过、被收回，或者过期了。\n可以请对方再发一个。',
    title: (name: string) => `「${name}」`,
    whoIsHere: (names: string) => `${names} 在这里等你。`,
    nameLabel: '大家怎么称呼你？',
    enter: '进来吧',
    entering: '正在进入…',
    haveAccount: '我有账号，用邮箱登录',
    guestNote: '不需要注册。以后想换手机也能找回，可以在「我」里绑定邮箱。',
  },
  me: {
    title: '我',
    nameLabel: '大家怎么称呼你',
    guestTitle: '你现在是访客',
    guestHint: '访客身份只存在这台设备的这个浏览器里。绑定邮箱后，换手机、清缓存也不会丢。',
    bindEmail: '绑定邮箱',
    bindSent: (email: string) => `验证码已经发到 ${email}。`,
    bindDone: '已经绑定好了。',
    emailLine: (email: string) => `登录邮箱：${email}`,
    signOut: '退出登录',
    signOutGuestWarn: '你还没绑定邮箱，退出后这个访客身份就找不回来了。确定退出吗？',
  },
} as const;

export default zhCN;
