import { execSync } from 'node:child_process';
import { BASE, launch, phone, login, createUs, SHOTS, FIXTURES } from './lib.mjs';
const shots = process.argv[2] ?? SHOTS;
const errors = [];
const browser = await launch();
const a = await phone(browser, errors, 'A');
await login(a, `ex${Date.now()}@example.com`, '导');
const us = await createUs(a, '照片测试');
await a.goto(`${BASE}/me`);
await a.getByRole('button', { name: '头像' }).click();
await a.locator('.sheet input[type=file]').nth(1).setInputFiles(`${FIXTURES}/photo_wall.jpg`);
await a.locator('.me-portrait .painted-photo-plain').waitFor();
await a.goto(`${BASE}/us/${us}`);
await a.getByRole('button', { name: '这段关系的照片' }).click();
await a.locator('.sheet input[type=file]').nth(1).setInputFiles(`${FIXTURES}/photo_sea.jpg`);
await a.locator('.cover .painted-photo-plain').waitFor();
await a.goto(`${BASE}/me/export`);
const [dl] = await Promise.all([a.waitForEvent('download'), a.click('button.primary')]);
await dl.saveAs(`${shots}/export2.zip`);
const listing = execSync(`unzip -l ${shots}/export2.zip`).toString();
if (!/media\/avatars\//.test(listing)) throw new Error('avatar missing from export\n' + listing);
if (!/media\/covers\//.test(listing)) throw new Error('relationship photo missing from export\n' + listing);
console.log(listing.split('\n').filter((l) => /avatars|covers/.test(l)).join('\n'));
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
